# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aca353c052b7ef4fbe6aa1e8bf18f54cf44ce86c4c361c238b1e0783d072b42c96b18dfa0d6da73c91244c6b142512a546683311a55d0293e54dcf0167232cc

test:
  secret_key_base: f0d7ba8bfc5a343a6a128554fc08d8ece5dda92b57e780b9dba49cdf9e0de5a90ab5886617fd5021a7cc2ea9e9e2f24bcc55f6911d49663e8dc932897fd85c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
